config/routes.rb
Rails.application.routes.draw do
  root "instruments#index"
  
  devise_for :users
  
  resources :instruments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user

  #validates :name { not_nil}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected 
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:edit, :show, :update, :destroy]

  def index
    @instruments = current_user.instruments.all 
  end

  def show
  end

  def new
    @instrument = Instrument.new 
  end

  def create
    @instrument = current_user.instruments.new(instrument_params)
    if @instrument.save
      flash[:success] = "Instrument Added"
      redirect_to instruments_path
    else
      flash[:error] = "Error #{@instrument.errors.full_messages.join("\n")}"
      render :new 
    end
  end

  def edit

  end

  def update
    
    if @instrument.update(instrument_params)
      redirect_to instruments_path
    else
      render :edit
    end
  end

  def destroy
    @instrument.destroy
    redirect_to instruments_path
  end

  private 
  def instrument_params
    params.require(:instrument).permit(:name)
  end

  def set_instrument
    @instrument = current_user.instruments.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/edit.html.erb
<h1>Edit Instrument</h1>
<%= form_with(model: @instrument, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Instrument Name" %>
  </div>
  <%= f.submit class: "waves-effect waves-light btn blue darken-4" %>
<% end %>

app/views/instruments/index.html.erb
<h1>Instruments</h1>
<br />
<h3>Welcome <%= current_user.first_name %></h3>
<h4>Your Instruments:</h4>
<%= link_to 'Add Instrument', new_instrument_path %>
<ul>
<li>
<% @instruments.each do |instrument| %>
  <%= instrument.name %><br />
  <%= link_to 'Edit', edit_instrument_path(instrument) %> | 
  <%= link_to 'Remove', instrument_path(instrument), method: :delete %><br />
<% end %>
</li>
</ul>

app/views/instruments/new.html.erb
<h1>Add Instrument</h1>
<%= form_with(model: @instrument, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Instrument Name" %>
  </div>
  <%= f.submit class: "waves-effect waves-light btn blue darken-4" %>
<% end %>

app/views/instruments/show.html.erb
<h1>Instruments#show</h1>
<p>Find me in app/views/instruments/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="blue lighten-1">
    <div class="nav-wrapper">
      <%= link_to 'Instrument Tracker', instruments_path, class: "brand-logo" %>
      <a href="#" class="brand-logo">Instrument Tracker</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li>
            <%= link_to 'Instruments', instruments_path %>
          </li>
          <li>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </li>       
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsInstrument</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>